// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MimoShop.Data;

#nullable disable

namespace MimoShop.Migrations
{
    [DbContext(typeof(MimoShopDbContext))]
    [Migration("20260604215558_Slice4And5")]
    partial class Slice4And5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MimoShop.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Telegram")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("WhatsApp")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("MimoShop.Models.InventoryPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("IsStocked")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PartType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitCostPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitSalePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Brand", "Model", "PartType", "Variant")
                        .IsUnique();

                    b.ToTable("InventoryParts");
                });

            modelBuilder.Entity("MimoShop.Models.InventoryStockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByUsername")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("InventoryPartId")
                        .HasColumnType("int");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuantityChange")
                        .HasColumnType("int");

                    b.Property<int?>("RepairPartUsageId")
                        .HasColumnType("int");

                    b.Property<int?>("RepairTicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InventoryPartId");

                    b.HasIndex("RepairPartUsageId");

                    b.HasIndex("RepairTicketId");

                    b.ToTable("InventoryStockMovements");
                });

            modelBuilder.Entity("MimoShop.Models.RepairPartUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUsername")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("InventoryPartId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOnDemand")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PartType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RepairTicketId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("UnitCostPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitSalePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("InventoryPartId");

                    b.HasIndex("RepairTicketId");

                    b.ToTable("RepairPartUsages");
                });

            modelBuilder.Entity("MimoShop.Models.RepairStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedByUsername")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("RepairTicketId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("RepairTicketId");

                    b.ToTable("RepairStatusHistories");
                });

            modelBuilder.Entity("MimoShop.Models.RepairTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AssignedWorkerName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("AssignedWorkerUsername")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("DeviceBrand")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("DeviceModel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("EstimatedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("JobCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ProblemDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("JobCode")
                        .IsUnique();

                    b.ToTable("RepairTickets");
                });

            modelBuilder.Entity("MimoShop.Models.StaffMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("StaffMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "صاحب المحل",
                            PasswordHash = "D1FF07603ECECF1A10F3A4D9E9A9250A549EE45DC6851A47CE3CDA183A8E4BFE",
                            Role = "Owner",
                            Salt = "mimoshop-v1-owner",
                            Username = "owner"
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "العامل 1",
                            PasswordHash = "550C8B3DBB4C0CDE5D49120D06729FE6591FE0C7D7392F045AE75DF3C22DD5D3",
                            Role = "Worker",
                            Salt = "mimoshop-v1-worker1",
                            Username = "worker1"
                        },
                        new
                        {
                            Id = 3,
                            DisplayName = "العامل 2",
                            PasswordHash = "1F90ADDB5ADB8FC4E4F3149FC1B4E9421A3587A5D1807F71E0083ADB93AEBFAF",
                            Role = "Worker",
                            Salt = "mimoshop-v1-worker2",
                            Username = "worker2"
                        });
                });

            modelBuilder.Entity("MimoShop.Models.InventoryStockMovement", b =>
                {
                    b.HasOne("MimoShop.Models.InventoryPart", "InventoryPart")
                        .WithMany()
                        .HasForeignKey("InventoryPartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MimoShop.Models.RepairPartUsage", "RepairPartUsage")
                        .WithMany()
                        .HasForeignKey("RepairPartUsageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MimoShop.Models.RepairTicket", "RepairTicket")
                        .WithMany()
                        .HasForeignKey("RepairTicketId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("InventoryPart");

                    b.Navigation("RepairPartUsage");

                    b.Navigation("RepairTicket");
                });

            modelBuilder.Entity("MimoShop.Models.RepairPartUsage", b =>
                {
                    b.HasOne("MimoShop.Models.InventoryPart", "InventoryPart")
                        .WithMany("RepairPartUsages")
                        .HasForeignKey("InventoryPartId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MimoShop.Models.RepairTicket", "RepairTicket")
                        .WithMany("PartUsages")
                        .HasForeignKey("RepairTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryPart");

                    b.Navigation("RepairTicket");
                });

            modelBuilder.Entity("MimoShop.Models.RepairStatusHistory", b =>
                {
                    b.HasOne("MimoShop.Models.RepairTicket", "RepairTicket")
                        .WithMany("StatusHistory")
                        .HasForeignKey("RepairTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RepairTicket");
                });

            modelBuilder.Entity("MimoShop.Models.RepairTicket", b =>
                {
                    b.HasOne("MimoShop.Models.Customer", "Customer")
                        .WithMany("RepairTickets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("MimoShop.Models.Customer", b =>
                {
                    b.Navigation("RepairTickets");
                });

            modelBuilder.Entity("MimoShop.Models.InventoryPart", b =>
                {
                    b.Navigation("RepairPartUsages");
                });

            modelBuilder.Entity("MimoShop.Models.RepairTicket", b =>
                {
                    b.Navigation("PartUsages");

                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
