// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MimoShop.Data;

#nullable disable

namespace MimoShop.Migrations
{
    [DbContext(typeof(MimoShopDbContext))]
    [Migration("20260717083310_AddPublicStorefront")]
    partial class AddPublicStorefront
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MimoShop.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayNameAr")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayNameAr = "سامسونج",
                            ImageUrl = "",
                            IsActive = true,
                            Name = "Samsung",
                            SortOrder = 10,
                            ThumbnailUrl = ""
                        },
                        new
                        {
                            Id = 2,
                            DisplayNameAr = "أبل",
                            ImageUrl = "",
                            IsActive = true,
                            Name = "Apple",
                            SortOrder = 20,
                            ThumbnailUrl = ""
                        },
                        new
                        {
                            Id = 3,
                            DisplayNameAr = "شاومي",
                            ImageUrl = "",
                            IsActive = true,
                            Name = "Xiaomi",
                            SortOrder = 30,
                            ThumbnailUrl = ""
                        },
                        new
                        {
                            Id = 4,
                            DisplayNameAr = "هواوي",
                            ImageUrl = "",
                            IsActive = true,
                            Name = "Huawei",
                            SortOrder = 40,
                            ThumbnailUrl = ""
                        },
                        new
                        {
                            Id = 5,
                            DisplayNameAr = "أوبو",
                            ImageUrl = "",
                            IsActive = true,
                            Name = "Oppo",
                            SortOrder = 50,
                            ThumbnailUrl = ""
                        },
                        new
                        {
                            Id = 6,
                            DisplayNameAr = "ريلمي",
                            ImageUrl = "",
                            IsActive = true,
                            Name = "Realme",
                            SortOrder = 60,
                            ThumbnailUrl = ""
                        },
                        new
                        {
                            Id = 7,
                            DisplayNameAr = "إنفينيكس",
                            ImageUrl = "",
                            IsActive = true,
                            Name = "Infinix",
                            SortOrder = 70,
                            ThumbnailUrl = ""
                        },
                        new
                        {
                            Id = 8,
                            DisplayNameAr = "تكنو",
                            ImageUrl = "",
                            IsActive = true,
                            Name = "Tecno",
                            SortOrder = 80,
                            ThumbnailUrl = ""
                        },
                        new
                        {
                            Id = 9,
                            DisplayNameAr = "نوكيا",
                            ImageUrl = "",
                            IsActive = true,
                            Name = "Nokia",
                            SortOrder = 90,
                            ThumbnailUrl = ""
                        },
                        new
                        {
                            Id = 10,
                            DisplayNameAr = "ون بلس",
                            ImageUrl = "",
                            IsActive = true,
                            Name = "OnePlus",
                            SortOrder = 100,
                            ThumbnailUrl = ""
                        });
                });

            modelBuilder.Entity("MimoShop.Models.Commune", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameFr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("WilayaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WilayaId", "NameAr")
                        .IsUnique();

                    b.ToTable("Communes");
                });

            modelBuilder.Entity("MimoShop.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Telegram")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("WhatsApp")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("MimoShop.Models.InventoryPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsStocked")
                        .HasColumnType("bit");

                    b.Property<int>("PartTypeId")
                        .HasColumnType("int");

                    b.Property<int>("PartVariantId")
                        .HasColumnType("int");

                    b.Property<int>("PhoneModelId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("UnitCostPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitSalePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PartTypeId");

                    b.HasIndex("PartVariantId");

                    b.HasIndex("PhoneModelId");

                    b.HasIndex("BrandId", "PhoneModelId", "PartTypeId", "PartVariantId")
                        .IsUnique();

                    b.ToTable("InventoryParts");
                });

            modelBuilder.Entity("MimoShop.Models.InventoryStockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByUsername")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("InventoryPartId")
                        .HasColumnType("int");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuantityChange")
                        .HasColumnType("int");

                    b.Property<int?>("RepairPartUsageId")
                        .HasColumnType("int");

                    b.Property<int?>("RepairTicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InventoryPartId");

                    b.HasIndex("RepairPartUsageId");

                    b.HasIndex("RepairTicketId");

                    b.ToTable("InventoryStockMovements");
                });

            modelBuilder.Entity("MimoShop.Models.PartType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayNameAr")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PartTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayNameAr = "شاشة",
                            ImageUrl = "",
                            IsActive = true,
                            Name = "Screen",
                            SortOrder = 10,
                            ThumbnailUrl = ""
                        },
                        new
                        {
                            Id = 2,
                            DisplayNameAr = "بطارية",
                            ImageUrl = "",
                            IsActive = true,
                            Name = "Battery",
                            SortOrder = 20,
                            ThumbnailUrl = ""
                        },
                        new
                        {
                            Id = 3,
                            DisplayNameAr = "غطاء خلفي",
                            ImageUrl = "",
                            IsActive = true,
                            Name = "Back cover",
                            SortOrder = 30,
                            ThumbnailUrl = ""
                        },
                        new
                        {
                            Id = 4,
                            DisplayNameAr = "منفذ شحن",
                            ImageUrl = "",
                            IsActive = true,
                            Name = "Charging port",
                            SortOrder = 40,
                            ThumbnailUrl = ""
                        },
                        new
                        {
                            Id = 5,
                            DisplayNameAr = "كاميرا",
                            ImageUrl = "",
                            IsActive = true,
                            Name = "Camera",
                            SortOrder = 50,
                            ThumbnailUrl = ""
                        },
                        new
                        {
                            Id = 6,
                            DisplayNameAr = "سماعة",
                            ImageUrl = "",
                            IsActive = true,
                            Name = "Speaker",
                            SortOrder = 60,
                            ThumbnailUrl = ""
                        },
                        new
                        {
                            Id = 7,
                            DisplayNameAr = "مايكروفون",
                            ImageUrl = "",
                            IsActive = true,
                            Name = "Microphone",
                            SortOrder = 70,
                            ThumbnailUrl = ""
                        });
                });

            modelBuilder.Entity("MimoShop.Models.PartVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayNameAr")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PartVariants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayNameAr = "أصلي",
                            IsActive = true,
                            Name = "Original OEM",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 2,
                            DisplayNameAr = "متوافق",
                            IsActive = true,
                            Name = "Compatible",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = 3,
                            DisplayNameAr = "مجدد",
                            IsActive = true,
                            Name = "Refurbished",
                            SortOrder = 30
                        });
                });

            modelBuilder.Entity("MimoShop.Models.PhoneModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("DisplayNameAr")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId", "Name")
                        .IsUnique();

                    b.ToTable("PhoneModels");
                });

            modelBuilder.Entity("MimoShop.Models.RepairPartUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUsername")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("InventoryPartId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOnDemand")
                        .HasColumnType("bit");

                    b.Property<string>("PartTypeName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PartVariantName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PhoneModelName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RepairTicketId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("UnitCostPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitSalePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InventoryPartId");

                    b.HasIndex("RepairTicketId");

                    b.ToTable("RepairPartUsages");
                });

            modelBuilder.Entity("MimoShop.Models.RepairStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedByUsername")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("RepairTicketId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("RepairTicketId");

                    b.ToTable("RepairStatusHistories");
                });

            modelBuilder.Entity("MimoShop.Models.RepairTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AssignedWorkerName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("AssignedWorkerUsername")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("DeviceBrand")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("DeviceModel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("EstimatedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("JobCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ProblemDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("JobCode")
                        .IsUnique();

                    b.ToTable("RepairTickets");
                });

            modelBuilder.Entity("MimoShop.Models.ShopOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CancelledReason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("CommuneId")
                        .HasColumnType("int");

                    b.Property<string>("CommuneName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CommuneNameFr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("CustomerWhatsApp")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("ReturnReason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ShipmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ShippedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ShippingFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("New");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WilayaId")
                        .HasColumnType("int");

                    b.Property<string>("WilayaName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CommuneId");

                    b.HasIndex("OrderCode")
                        .IsUnique();

                    b.HasIndex("WilayaId");

                    b.ToTable("ShopOrders");
                });

            modelBuilder.Entity("MimoShop.Models.ShopOrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("InventoryPartId")
                        .HasColumnType("int");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PartDisplayName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PartTypeName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ShopOrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VariantName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("InventoryPartId");

                    b.HasIndex("ShopOrderId");

                    b.ToTable("ShopOrderLines");
                });

            modelBuilder.Entity("MimoShop.Models.ShopSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LatinName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("OpeningHours")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("TelegramHandle")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("WhatsApp")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("ShopSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "الجزائر",
                            LatinName = "MimoShop",
                            Name = "ميمو شوب",
                            OpeningHours = "السبت - الخميس 09:00 - 18:00",
                            Phone = "000 00 00 00",
                            TelegramHandle = "@mimoshop_bot",
                            WhatsApp = ""
                        });
                });

            modelBuilder.Entity("MimoShop.Models.StaffMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("StaffMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "مدير النظام",
                            IsActive = true,
                            PasswordHash = "D1FF07603ECECF1A10F3A4D9E9A9250A549EE45DC6851A47CE3CDA183A8E4BFE",
                            Role = "SuperAdmin",
                            Salt = "mimoshop-v1-owner",
                            Username = "owner"
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "العامل 1",
                            IsActive = true,
                            PasswordHash = "550C8B3DBB4C0CDE5D49120D06729FE6591FE0C7D7392F045AE75DF3C22DD5D3",
                            Role = "Worker",
                            Salt = "mimoshop-v1-worker1",
                            Username = "worker1"
                        },
                        new
                        {
                            Id = 3,
                            DisplayName = "العامل 2",
                            IsActive = true,
                            PasswordHash = "1F90ADDB5ADB8FC4E4F3149FC1B4E9421A3587A5D1807F71E0083ADB93AEBFAF",
                            Role = "Worker",
                            Salt = "mimoshop-v1-worker2",
                            Username = "worker2"
                        });
                });

            modelBuilder.Entity("MimoShop.Models.Wilaya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameFr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ShippingFee")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("NameAr")
                        .IsUnique();

                    b.HasIndex("NameFr")
                        .IsUnique();

                    b.ToTable("Wilayas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "01",
                            IsActive = true,
                            NameAr = "أدرار",
                            NameFr = "Adrar",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 2,
                            Code = "02",
                            IsActive = true,
                            NameAr = "الشلف",
                            NameFr = "Chlef",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 3,
                            Code = "03",
                            IsActive = true,
                            NameAr = "الأغواط",
                            NameFr = "Laghouat",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 4,
                            Code = "04",
                            IsActive = true,
                            NameAr = "أم البواقي",
                            NameFr = "Oum El Bouaghi",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 5,
                            Code = "05",
                            IsActive = true,
                            NameAr = "باتنة",
                            NameFr = "Batna",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 6,
                            Code = "06",
                            IsActive = true,
                            NameAr = "بجاية",
                            NameFr = "Béjaïa",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 7,
                            Code = "07",
                            IsActive = true,
                            NameAr = "بسكرة",
                            NameFr = "Biskra",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 8,
                            Code = "08",
                            IsActive = true,
                            NameAr = "بشار",
                            NameFr = "Béchar",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 9,
                            Code = "09",
                            IsActive = true,
                            NameAr = "البليدة",
                            NameFr = "Blida",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 10,
                            Code = "10",
                            IsActive = true,
                            NameAr = "البويرة",
                            NameFr = "Bouira",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 11,
                            Code = "11",
                            IsActive = true,
                            NameAr = "تمنراست",
                            NameFr = "Tamanrasset",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 12,
                            Code = "12",
                            IsActive = true,
                            NameAr = "تبسة",
                            NameFr = "Tébessa",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 13,
                            Code = "13",
                            IsActive = true,
                            NameAr = "تلمسان",
                            NameFr = "Tlemcen",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 14,
                            Code = "14",
                            IsActive = true,
                            NameAr = "تيارت",
                            NameFr = "Tiaret",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 15,
                            Code = "15",
                            IsActive = true,
                            NameAr = "تيزي وزو",
                            NameFr = "Tizi Ouzou",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 16,
                            Code = "16",
                            IsActive = true,
                            NameAr = "الجزائر",
                            NameFr = "Alger",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 17,
                            Code = "17",
                            IsActive = true,
                            NameAr = "الجلفة",
                            NameFr = "Djelfa",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 18,
                            Code = "18",
                            IsActive = true,
                            NameAr = "جيجل",
                            NameFr = "Jijel",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 19,
                            Code = "19",
                            IsActive = true,
                            NameAr = "سطيف",
                            NameFr = "Sétif",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 20,
                            Code = "20",
                            IsActive = true,
                            NameAr = "سعيدة",
                            NameFr = "Saïda",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 21,
                            Code = "21",
                            IsActive = true,
                            NameAr = "سكيكدا",
                            NameFr = "Skikda",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 22,
                            Code = "22",
                            IsActive = true,
                            NameAr = "سيدي بلعباس",
                            NameFr = "Sidi Bel Abbès",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 23,
                            Code = "23",
                            IsActive = true,
                            NameAr = "عنابة",
                            NameFr = "Annaba",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 24,
                            Code = "24",
                            IsActive = true,
                            NameAr = "قالمة",
                            NameFr = "Guelma",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 25,
                            Code = "25",
                            IsActive = true,
                            NameAr = "قسنطينة",
                            NameFr = "Constantine",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 26,
                            Code = "26",
                            IsActive = true,
                            NameAr = "المدية",
                            NameFr = "Médéa",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 27,
                            Code = "27",
                            IsActive = true,
                            NameAr = "مستغانم",
                            NameFr = "Mostaganem",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 28,
                            Code = "28",
                            IsActive = true,
                            NameAr = "المسيلة",
                            NameFr = "M'Sila",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 29,
                            Code = "29",
                            IsActive = true,
                            NameAr = "معسكر",
                            NameFr = "Mascara",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 30,
                            Code = "30",
                            IsActive = true,
                            NameAr = "ورقلة",
                            NameFr = "Ouargla",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 31,
                            Code = "31",
                            IsActive = true,
                            NameAr = "وهران",
                            NameFr = "Oran",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 32,
                            Code = "32",
                            IsActive = true,
                            NameAr = "البيض",
                            NameFr = "El Bayadh",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 33,
                            Code = "33",
                            IsActive = true,
                            NameAr = "إليزي",
                            NameFr = "Illizi",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 34,
                            Code = "34",
                            IsActive = true,
                            NameAr = "برج بوعريريج",
                            NameFr = "Bordj Bou Arréridj",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 35,
                            Code = "35",
                            IsActive = true,
                            NameAr = "بومرداس",
                            NameFr = "Boumerdès",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 36,
                            Code = "36",
                            IsActive = true,
                            NameAr = "الطريف",
                            NameFr = "El Tarf",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 37,
                            Code = "37",
                            IsActive = true,
                            NameAr = "تندوف",
                            NameFr = "Tindouf",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 38,
                            Code = "38",
                            IsActive = true,
                            NameAr = "تيسمسيلت",
                            NameFr = "Tissemsilt",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 39,
                            Code = "39",
                            IsActive = true,
                            NameAr = "الوادي",
                            NameFr = "El Oued",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 40,
                            Code = "40",
                            IsActive = true,
                            NameAr = "خنشلة",
                            NameFr = "Khenchela",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 41,
                            Code = "41",
                            IsActive = true,
                            NameAr = "سوق أهراس",
                            NameFr = "Souk Ahras",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 42,
                            Code = "42",
                            IsActive = true,
                            NameAr = "تيبازة",
                            NameFr = "Tipaza",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 43,
                            Code = "43",
                            IsActive = true,
                            NameAr = "ميلة",
                            NameFr = "Mila",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 44,
                            Code = "44",
                            IsActive = true,
                            NameAr = "عين الدفلى",
                            NameFr = "Aïn Defla",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 45,
                            Code = "45",
                            IsActive = true,
                            NameAr = "النعامة",
                            NameFr = "Naâma",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 46,
                            Code = "46",
                            IsActive = true,
                            NameAr = "عين تموشنت",
                            NameFr = "Aïn Témouchent",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 47,
                            Code = "47",
                            IsActive = true,
                            NameAr = "غرداية",
                            NameFr = "Ghardaïa",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 48,
                            Code = "48",
                            IsActive = true,
                            NameAr = "غليزان",
                            NameFr = "Relizane",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 49,
                            Code = "49",
                            IsActive = true,
                            NameAr = "تيميمون",
                            NameFr = "Timimoun",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 50,
                            Code = "50",
                            IsActive = true,
                            NameAr = "برج باجي مختار",
                            NameFr = "Bordj Badji Mokhtar",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 51,
                            Code = "51",
                            IsActive = true,
                            NameAr = "أولاد جلال",
                            NameFr = "Ouled Djellal",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 52,
                            Code = "52",
                            IsActive = true,
                            NameAr = "بني عباس",
                            NameFr = "Béni Abbès",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 53,
                            Code = "53",
                            IsActive = true,
                            NameAr = "عين صالح",
                            NameFr = "In Salah",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 54,
                            Code = "54",
                            IsActive = true,
                            NameAr = "عين قزام",
                            NameFr = "In Guezzam",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 55,
                            Code = "55",
                            IsActive = true,
                            NameAr = "تقرت",
                            NameFr = "Touggourt",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 56,
                            Code = "56",
                            IsActive = true,
                            NameAr = "جانت",
                            NameFr = "Djanet",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 57,
                            Code = "57",
                            IsActive = true,
                            NameAr = "المغير",
                            NameFr = "El M'Ghair",
                            ShippingFee = 0m
                        },
                        new
                        {
                            Id = 58,
                            Code = "58",
                            IsActive = true,
                            NameAr = "المنية",
                            NameFr = "El Meniaa",
                            ShippingFee = 0m
                        });
                });

            modelBuilder.Entity("MimoShop.Models.Commune", b =>
                {
                    b.HasOne("MimoShop.Models.Wilaya", "Wilaya")
                        .WithMany("Communes")
                        .HasForeignKey("WilayaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Wilaya");
                });

            modelBuilder.Entity("MimoShop.Models.InventoryPart", b =>
                {
                    b.HasOne("MimoShop.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MimoShop.Models.PartType", "PartType")
                        .WithMany()
                        .HasForeignKey("PartTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MimoShop.Models.PartVariant", "PartVariant")
                        .WithMany()
                        .HasForeignKey("PartVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MimoShop.Models.PhoneModel", "PhoneModel")
                        .WithMany()
                        .HasForeignKey("PhoneModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("PartType");

                    b.Navigation("PartVariant");

                    b.Navigation("PhoneModel");
                });

            modelBuilder.Entity("MimoShop.Models.InventoryStockMovement", b =>
                {
                    b.HasOne("MimoShop.Models.InventoryPart", "InventoryPart")
                        .WithMany()
                        .HasForeignKey("InventoryPartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MimoShop.Models.RepairPartUsage", "RepairPartUsage")
                        .WithMany()
                        .HasForeignKey("RepairPartUsageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MimoShop.Models.RepairTicket", "RepairTicket")
                        .WithMany()
                        .HasForeignKey("RepairTicketId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("InventoryPart");

                    b.Navigation("RepairPartUsage");

                    b.Navigation("RepairTicket");
                });

            modelBuilder.Entity("MimoShop.Models.PhoneModel", b =>
                {
                    b.HasOne("MimoShop.Models.Brand", "Brand")
                        .WithMany("PhoneModels")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("MimoShop.Models.RepairPartUsage", b =>
                {
                    b.HasOne("MimoShop.Models.InventoryPart", "InventoryPart")
                        .WithMany("RepairPartUsages")
                        .HasForeignKey("InventoryPartId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MimoShop.Models.RepairTicket", "RepairTicket")
                        .WithMany("PartUsages")
                        .HasForeignKey("RepairTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryPart");

                    b.Navigation("RepairTicket");
                });

            modelBuilder.Entity("MimoShop.Models.RepairStatusHistory", b =>
                {
                    b.HasOne("MimoShop.Models.RepairTicket", "RepairTicket")
                        .WithMany("StatusHistory")
                        .HasForeignKey("RepairTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RepairTicket");
                });

            modelBuilder.Entity("MimoShop.Models.RepairTicket", b =>
                {
                    b.HasOne("MimoShop.Models.Customer", "Customer")
                        .WithMany("RepairTickets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("MimoShop.Models.ShopOrder", b =>
                {
                    b.HasOne("MimoShop.Models.Commune", "Commune")
                        .WithMany()
                        .HasForeignKey("CommuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MimoShop.Models.Wilaya", "Wilaya")
                        .WithMany()
                        .HasForeignKey("WilayaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Commune");

                    b.Navigation("Wilaya");
                });

            modelBuilder.Entity("MimoShop.Models.ShopOrderLine", b =>
                {
                    b.HasOne("MimoShop.Models.InventoryPart", "InventoryPart")
                        .WithMany()
                        .HasForeignKey("InventoryPartId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MimoShop.Models.ShopOrder", "ShopOrder")
                        .WithMany("Lines")
                        .HasForeignKey("ShopOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryPart");

                    b.Navigation("ShopOrder");
                });

            modelBuilder.Entity("MimoShop.Models.Brand", b =>
                {
                    b.Navigation("PhoneModels");
                });

            modelBuilder.Entity("MimoShop.Models.Customer", b =>
                {
                    b.Navigation("RepairTickets");
                });

            modelBuilder.Entity("MimoShop.Models.InventoryPart", b =>
                {
                    b.Navigation("RepairPartUsages");
                });

            modelBuilder.Entity("MimoShop.Models.RepairTicket", b =>
                {
                    b.Navigation("PartUsages");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("MimoShop.Models.ShopOrder", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("MimoShop.Models.Wilaya", b =>
                {
                    b.Navigation("Communes");
                });
#pragma warning restore 612, 618
        }
    }
}
